# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Marketplace Hacks
founder: Demircan Celebi
description: Learn how to build and scale online marketplaces from experience.<br>Get tips to your inbox.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.marketplacehacks.com" # the base hostname & protocol for your site
twitter_username: demircancelebi

# Build settings
markdown: kramdown
permalink: /:year/:month/:title
